name: Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ai-notebook/frontend/package-lock.json
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install frontend dependencies
      working-directory: ./ai-notebook/frontend
      run: npm ci
      
    - name: Build frontend
      working-directory: ./ai-notebook/frontend
      run: npm run build
      
    - name: Install backend dependencies
      working-directory: ./ai-notebook/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test backend
      working-directory: ./ai-notebook/backend
      run: |
        python -c "from app import create_app; app = create_app(); print('Backend app created successfully')"
        
    - name: Deploy to Vercel (Unified)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        vercel-args: '--prod'